### ISSUE TITLE
Make IZipArchiveFactory public

### ISSUE THREAD

**Issue by McTristan** [Testably/Testably.Abstractions#448]
Would it be possible to make the IZipArchiveFactory interface public and the ZipArchiveFactory class too?

It would be really help when using it with mocking frameworks.

I would like to use dependency injection and the IZipArchiveFactory as constructor parameter so I can mock it and verify if specific methods of IZipArchive have been called.

As ZipArchive on IFileSystem is just an extension method it is hard to mock.

The existing functionality is good enough for integration tests but for a unit test I don't really need a "mock" file system with real zip files, I just want to verify if method XYZ of ZipArchive etc. was called with the correct parameters.

**Comment by vbreuss** [comment]
Hello @McTristan,

The [`IZipArchiveFactory`](https://github.com/Testably/Testably.Abstractions/blob/main/Source/Testably.Abstractions.Compression/IZipArchiveFactory.cs) interface is already public, so if you directly use the `IZipArchiveFactory` as a constructor parameter, you should be able to replace it with a mock without any changes.

Regarding making the [`ZipArchiveFactory`](https://github.com/Testably/Testably.Abstractions/blob/main/Source/Testably.Abstractions.Compression/ZipArchiveFactory.cs) class public:
The idea behind this is, that consumers should only use and rely on the public interfaces and this project provides two implementations. One that abstracts away the .NET implementation and one that provides a testable alternative. How would it simplify your unit tests, when the class would be public?

**Comment by McTristan** [comment]
Hello Valentin,

I don't see how the public interface would help me. This way I would need to re-implement the standard implementation.
I can't register the default implementation (ZipArchiveFactory) via dependency injection because the class is internal.

What I would like to do is to the register the default implementation and mock it in a unit test. Right now the only thing that I can use is the extension method to the IFileSystem interface but this is even less practical as I can't mock it at all.

For IFileSystem it works just beautiful because there is a public standard implementation which I can register and use via services.AddTransient<IFileSystem,RealFileSystem>() and verify function calls via mocks and setups in unit tests.

**Comment by vbreuss** [comment]
I see your point, but there is another solution:
You can add the `IZipArchiveFactory` dependency to the services via
```csharp
services.AddTransient<IZipArchiveFactory>(sp => sp.GetRequiredService<IFileSystem>().ZipArchive());
```
or
```csharp
services.AddTransient<IZipArchiveFactory>(_ => new RealFileSystem().ZipArchive());
```

Would this solve your problem?

**Comment by McTristan** [comment]
this seems to work indeed though it isn't ideal, however I managed to setup all mocks successfully now. Thank you for your help!
